# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sajjad Day To Day
email: smkbhd@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  | I have learned some stuff these years.
  | Life sucks, Life is full of pain.
  | My key is future but I also need to enjoy the moment.
  | change doesnt happen in a day
  | I need to make this change day by day
  | I wont do it by myself
  | why?
  | cause I dont appreciate what I do every day and I | feel stuck.
  | I need to keep going
  | So now we are here for this
  | lets see where this gets us.
  | us, yes you and me. (maybe there is no you and it is | all me)

baseurl: "/My-Blog-Website" # the subpath of your site, e.g. /blog
url: "https://smkbhd2018.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
